In [40]:
import pandas as pd

In [41]:
# Q1
roll_no = "1024160015"
digits = []
for d in roll_no:
  digits.append(int(d))

fixed_entries = [
  {"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
  "keywords": "fee cost price charge", "category": "billing"},
  {"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
  "keywords": "password reset login", "category": "account"},
  {"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
  "keywords": "hours timing open time", "category": "general"},
  {"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.",
  "keywords": "pay payment upi fee", "category": "billing"},
]

category = ["billing", "account", "general"]

new_cat_1 = category[digits[-2] % 3] # printed earlier, account
new_cat_2 = category[digits[-1] % 3] # printed earlier, general

new_faq_1 = {"question": "How do I update my registered mobile number?", "answer": "Can't do it, sorry.", "keywords": "phone mobile number", "category": "account"}
new_faq_2 = {"question": "Hi!", "answer": "Hi!", "keywords": "greeting hello hi", "category": "general"}

final_entries = fixed_entries.copy()
final_entries.append(new_faq_1)
final_entries.append(new_faq_2)

df = pd.DataFrame(final_entries)

df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,How do I update my registered mobile number?,"Can't do it, sorry.",phone mobile number,account
5,Hi!,Hi!,greeting hello hi,general

In [42]:
# Q2
query = input("Query? ")

def scoring_function(query):
  df["score"] = 0.4 * df["question"].str.contains(query) + 0.5 * df["keywords"].str.contains(query)
  return df.sort_values(by="score", ascending=False).head(1) # made it head(1) because otherwise there wouldn't have been any difference between Q2 & Q6

scoring_function(query)

Query? hours

,question,answer,keywords,category,score
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general,0.9

In [43]:
# Q3
def same_category(category_name, df):
  return df[df["category"] == category_name]

same_category("billing", df)

,question,answer,keywords,category,score
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing,0.0
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing,0.0

In [44]:
# Q4
entry = int(input("Which entry do you want to update? "))
new_keyword = input("Enter a new keyword: ")
df.loc[entry, "keywords"] += (f" {new_keyword}")

df.to_csv(f"{roll_no}_faq_data.csv")
df

Which entry do you want to update? 2
Enter a new keyword: schedule

,question,answer,keywords,category,score
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing,0.0
1,how to reset password,Go to Settings > Reset Password.,password reset login,account,0.0
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time schedule,general,0.9
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing,0.0
4,How do I update my registered mobile number?,"Can't do it, sorry.",phone mobile number,account,0.0
5,Hi!,Hi!,greeting hello hi,general,0.0

In [45]:
# Q5
print(df.groupby("category").count())
print(df.groupby("category")["question"].count()) # if only count of questions is required

          question  answer  keywords  score
category
account          2       2         2      2
billing          2       2         2      2
general          2       2         2      2
category
account    2
billing    2
general    2
Name: question, dtype: int64

In [57]:
# Q6
def scoring_function(query):
  df["score"] = 0.4 * df["question"].str.contains(query) + 0.5 * df["keywords"].str.contains(query)
  highest_score = df["score"].max()
  return df[df["score"] == highest_score].sort_values(by="score", ascending=False)

scoring_function("fee")

,question,answer,keywords,category,score
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing,0.9
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing,0.9

In [58]:
scoring_function("password")

,question,answer,keywords,category,score
1,how to reset password,Go to Settings > Reset Password.,password reset login,account,0.9